print("What is your name human?")
name = input()
print("How old are you?")
age = input(int())
print("How tall are you?")
heigh = input(float())
print ("How much do you weigh?")
weight = input(int())
print(name(str)"you are ")