print("Please enter the number of lives.")
lives = input()
print()
print("Please enter the energy level.")
entryLevel = input()
print()
print("Please enter the shield level.")
shieldLevel = input()
print()
print()
print("Health has been set.")